// File generated by FlutterFire CLI
// Firebase configuration for KK360 project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isWindows) {
      return windows;
    }
    if (Platform.isLinux) {
      return linux;
    }
    if (Platform.isMacOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8rwUKxy6lQ_1vCX4R3BFNrGdi-QTnPcg',
    appId: '1:599863270326:android:98b00590ba650513d2ff17',
    messagingSenderId: '599863270326',
    projectId: 'kk360-69504',
    storageBucket: 'kk360-69504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rwUKxy6lQ_1vCX4R3BFNrGdi-QTnPcg',
    appId: '1:599863270326:ios:98b00590ba650513d2ff17',
    messagingSenderId: '599863270326',
    projectId: 'kk360-69504',
    storageBucket: 'kk360-69504.firebasestorage.app',
    iosBundleId: 'com.example.kk360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnop',
    appId: '1:599863270326:macos:xxxxxxxxxxxxxxxx',
    messagingSenderId: '599863270326',
    projectId: 'kk360-69504',
    storageBucket: 'kk360-69504.firebasestorage.app',
    iosBundleId: 'com.example.kk360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnop',
    appId: '1:599863270326:windows:xxxxxxxxxxxxxxxx',
    messagingSenderId: '599863270326',
    projectId: 'kk360-69504',
    storageBucket: 'kk360-69504.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC1234567890abcdefghijklmnop',
    appId: '1:599863270326:linux:xxxxxxxxxxxxxxxx',
    messagingSenderId: '599863270326',
    projectId: 'kk360-69504',
    storageBucket: 'kk360-69504.firebasestorage.app',
  );
}
